import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  about: [{type: 'autogenerated', dirName: 'about'}],

  'what-is-finops': [
    'introduction/what-is-finops',
    {
      type: 'link',
      label: 'FinOpsフレームワーク',
      href: 'https://finops-jp.github.io/docs/framework',
    },
    {
      type: 'link',
      label: 'FinOps用語',
      href: 'https://finops-jp.github.io/docs/assets/terminology',
    },
  ],

  framework: [
    {
      type: 'link',
      label: 'FinOpsとは',
      href: 'https://finops-jp.github.io/docs/introduction/what-is-finops',
    },
    {
      type: 'category',
      label: 'FinOpsフレームワーク',
      link: {
        type: 'doc',
        id: 'framework/index',
      },
      items: [
        'framework/principles',
        {
          type: 'category',
          label: 'FinOpsペルソナ',
          description: 'FinOpsの分野には、さまざまなペルソナが含まれます。それらのペルソナ、その役割、要件について詳しく理解します。',
          link: {
            type: 'doc',
            id: 'framework/personas/index',
          },
          items: [
            'framework/personas/finops-practitioner',
            'framework/personas/leadership',
            'framework/personas/product',
            'framework/personas/engineering',
            'framework/personas/finance',
            'framework/personas/procurement',
          ],
        },
        'framework/phases',
        'framework/maturity-model',
        {
          type: 'category',
          label: 'FinOpsドメイン',
          description: 'FinOpsドメインは、活動やナレッジの領域を表しています。FinOpsを採用するすべての組織は、すべてのFinOpsドメインで活動を行うことになります。',
          link: {
            type: 'doc',
            id: 'framework/domains/index',
          },
          items: [{type: 'autogenerated', dirName: 'framework/domains'}],
        },
        {
          type: 'category',
          label: 'FinOpsケイパビリティ',
          description: 'FinOpsケイパビリティは、対応するFinOpsドメインをサポートする機能的な活動領域を表しています。各ケイパビリティには、実際のFinOpsプラクティスに関連する定義、主要なペルソナ、パフォーマンスメトリクス、機能的なアクティビティが含まれています。',
          link: {
            type: 'doc',
            id: 'framework/capabilities/index',
          },
          items: [{type: 'autogenerated', dirName: 'framework/capabilities'}],
        },
        'framework/scopes',
      ],
    },
    {
      type: 'link',
      label: 'FinOps用語',
      href: 'https://finops-jp.github.io/docs/assets/terminology',
    },
  ],

  terminology: [
    'assets/terminology'
  ],
};

export default sidebars;
